typography_spectrum: 0.60983
color:
  brandColors:
    - '#000400'
    - '#fdc39b'
    - '#d49a74'
    - '#fffbc3'
    - '#744527'
  brandStrength: 0.4375
  lightness: 0.6506159291602671
  saturation: 0.6656268392689526
  rhythmicContrast: 0.03549519903026521
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5374
analytics:
  google: null
  facebook: null
  twitter: null
name: Social Media Network Group
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SMNG
purpose: []
